### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by bigoss** [beetleman/mezzanine_bootswatch#2]
For some reason I can't add mezzanine_bootswatch to installed apps while internationalization is on.
I get following error :  "The translation infrastructure cannot be initialized before the "
django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.

beautifulsoup4==4.4.1
bleach==1.4.3
chardet==2.3.0
Django==1.9.7
django-contrib-comments==1.7.1
django-modeltranslation==0.11
filebrowser-safe==0.4.3
future==0.15.2
grappelli-safe==0.4.2
html5lib==0.9999999
Mezzanine==4.1.0
mezzanine-bootswatch==0.1.0
oauthlib==1.1.2
Pillow==3.3.0
pytz==2016.4
requests==2.10.0
requests-oauthlib==0.6.1
six==1.10.0
tzlocal==1.2.2

INSTALLED_APPS = (
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.redirects",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "django.contrib.staticfiles",
    "modeltranslation",
    "mezzanine_bootswatch",
    "mezzanine.boot",
    "mezzanine.conf",
    "mezzanine.core",
    "mezzanine.generic",
    "mezzanine.pages",
    #"mezzanine.blog",
    "mezzanine.forms",
    "mezzanine.galleries",
    #"mezzanine.twitter",
    # "mezzanine.accounts",
    # "mezzanine.mobile",

**Comment by beetleman** [comment]
Fixed
